# Generated by Django 4.0.8 on 2022-11-24 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorified', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['categorified'],
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authors', models.CharField(max_length=200)),
                ('isbn', isbn_field.fields.ISBNField(max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('active', models.BooleanField(default=True)),
                ('book_id', models.PositiveIntegerField()),
                ('book_title', models.CharField(max_length=200)),
                ('edition', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='admins/')),
                ('quantity', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalogue.category')),
            ],
            options={
                'permissions': [('AdminBksPermissions', 'Can add library Books')],
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordered_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.catalogue')),
            ],
        ),
        migrations.CreateModel(
            name='AdminBookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('admin_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookk_reviews', to='catalogue.catalogue')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
