# Generated by Django 4.0.8 on 2022-11-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_rename_adminbookreview_cataloguereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
