# Generated by Django 4.0.8 on 2022-11-25 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0004_catalogue_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cataloguereview',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='catalogue',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cataloguereview',
            name='admin_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to='catalogue.catalogue'),
        ),
    ]
