# Generated by Django 4.0.8 on 2022-12-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_cataloguereview_options_catalogue_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
