# Generated by Django 4.0.8 on 2022-12-08 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_catalogue_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='ordered_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_book', to='catalogue.catalogue'),
        ),
    ]
