# Generated by Django 4.0.8 on 2022-12-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_rename_ordered_book_borrow_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='book',
            new_name='ordered_book',
        ),
    ]
