# Generated by Django 4.0.8 on 2022-12-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_rename_book_borrow_ordered_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retured',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='catalogue.catalogue'),
        ),
    ]
