# Generated by Django 4.0.8 on 2022-11-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_adminbooks_category_book_time_review_time_borrow_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
