# Generated by Django 4.0.8 on 2022-11-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
