# Generated by Django 4.0.8 on 2022-11-18 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_book_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='author',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='ordered_book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='admin_book',
        ),
        migrations.AddField(
            model_name='book',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdminBooks',
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
