# Generated by Django 4.0.8 on 2022-11-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_remove_borrow_author_remove_borrow_ordered_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='time',
        ),
    ]
