# Generated by Django 4.0.8 on 2022-11-19 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_remove_book_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
