# Generated by Django 4.0.8 on 2022-11-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_book_time_alter_review_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='time',
        ),
        migrations.RemoveField(
            model_name='review',
            name='time',
        ),
    ]
