# Generated by Django 4.0.8 on 2022-11-20 03:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import isbn_field.fields
import isbn_field.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0016_remove_book_time_remove_review_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBooks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isbn', isbn_field.fields.ISBNField(max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('book_id', models.PositiveIntegerField()),
                ('book_title', models.CharField(max_length=200)),
                ('edition', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='admins/')),
                ('writer', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorified', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['categorified'],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 20, 3, 26, 55, 259600, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordered_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.adminbooks')),
            ],
        ),
        migrations.AddField(
            model_name='adminbooks',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='book.category'),
        ),
        migrations.CreateModel(
            name='AdminBookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('admin_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_book_reviews', to='book.adminbooks')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
