# Generated by Django 4.0.8 on 2022-11-20 03:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_adminbooks_category_review_time_borrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 20, 3, 29, 17, 323664, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
