# Generated by Django 4.0.8 on 2022-11-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_author_alter_book_time_alter_review_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='time',
        ),
        migrations.RemoveField(
            model_name='review',
            name='time',
        ),
    ]
