# Generated by Django 4.0.8 on 2022-11-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_alter_adminbooks_options_adminbooks_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('add author', 'can add an author')]},
        ),
        migrations.RemoveField(
            model_name='adminbooks',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='adminbooks',
            name='writer',
        ),
        migrations.AlterField(
            model_name='adminbooks',
            name='authors',
            field=models.ManyToManyField(blank=True, to='book.author'),
        ),
    ]
