# Generated by Django 4.0.8 on 2022-11-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_alter_author_options_remove_adminbooks_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminbooks',
            name='authors',
        ),
        migrations.AddField(
            model_name='adminbooks',
            name='authors',
            field=models.CharField(default='JD Salinger', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
