# Generated by Django 4.0.8 on 2022-11-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_remove_adminbooks_authors_adminbooks_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminbooks',
            name='category',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='author',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='ordered_book',
        ),
        migrations.DeleteModel(
            name='AdminBookReview',
        ),
        migrations.DeleteModel(
            name='AdminBooks',
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
