# Generated by Django 4.0.8 on 2022-12-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_alter_book_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='creator',
        ),
    ]
