# Generated by Django 4.0.8 on 2022-12-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
