# Generated by Django 4.0.8 on 2022-12-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_book_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
